
image: jdrouet/docker-with-buildx:stable

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:
- test&build
- update-gitops

sast:
  stage: test&build
include:
- template: Security/SAST.gitlab-ci.yml


build:
  stage: test&build
  script:
    - docker login registry.gitlab.com -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker buildx create --use
    - docker buildx build --push --platform amd64,arm64 --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} .


  only:
    - tags

update-gitops:
  stage: update-gitops

  before_script:
    - |
      REPO_URL=$(echo "$GITOPS_REPO_URL" | sed -e "s;https://;https://${GITOPS_USERNAME}:${GITOPS_PASSWORD}@;")

  script:
    -  apk add --no-cache git
    - |
      git clone $REPO_URL ;
      cd $GITOPS_MANIFETS_PATH ;
      sed -i 's/newTag: ".*"/newTag: "'$CI_COMMIT_TAG'"/' kustomization.yaml ;
      git config user.email "macu-dev@gmail.com" ;
      git config user.name "macu dev ci-cd" ;
      git add kustomization.yaml ;
      git commit -m "Update image tag to $CI_COMMIT_TAG" ;
      git push

  only:
    - tags
  dependencies:
    - build
    - sast
